[database]
host = "localhost"
port = 5432
database = "database_name"
username = "username"
password = "password"
max_connections = 10

[workers]
count = 4

[processing]
channel_name = "transaction_channel"
retry_attempts = 3
retry_delay_ms = 1000